### ISSUE TITLE
Prezentacja

### ISSUE THREAD

**Issue by ghost** [fletchPL/Project-X#9]
- [x] omówienie możliwości dla roli, dopisanie ich w skrócie do prezentacji

- [x] dodanie screenów layout'u

- [x] ustalenie kolejności prezentacji, zrobienie planu prezentacji

- [x] dodanie zdjęć 

- [x] uzupełnienie planu prezentacji

**Comment by ghost** [comment]
[Plan prezentacji](https://docs.google.com/document/d/155SFC2gpgs2x_et_bRlF4tRSqonj0KGlgZpQPoqItco/edit?usp=sharing)

Proszę o uzupełnianie planu prezentacji.

**Comment by mberento** [comment]
Do zmiany:
[opcjonalne] dodanie zdjęć 
według mnie wywalenie tego przybliżenia na postacie
w opisie funkcjonalności wyśrodkujmy chociaż te nazwy jeśli nic wiecej nie dodajemy
przydały sie jakieś wyniki tych ankiet, nawet fakeowe byle że zrobilismy
screeny layoutu

Przydałby sie wgl jakaś jaśniejsza ta prezentacja

**Comment by ghost** [comment]
[Godziny prezentacji](https://github.com/fletchPL/Project-X/files/909191/Plan_1_.prezentacji.1.pdf)

**Comment by fletchPL** [comment]
jak wyjdę z zajęć naniosę poprawki na prezentację :)
